symbol: BTCUSDT
category: linear  # bybit v5 category: linear | inverse | option | spot
mode: paper       # paper | live
risk:
  max_risk_per_trade_pct: 0.5
  daily_stop_r_multiple: -2.0
  cooldown_minutes: 3
  max_live_order_notional_krw: 200000.0
  usdt_krw_rate: 1400.0
  starting_equity: 10000.0
strategy:
  name: scalper_v1
  timeframe_entry: 1m
  timeframe_anchor: 5m
  ema_fast: 50
  ema_slow: 200
  atr_period: 14
  atr_mult_stop: 1.0
  partial_tp_r: 1.5
  trail_atr_mult: 2.0
  micro_high_lookback: 2
  time_stop_minutes: 30
  volume_ma_period: 20
  volume_threshold_ratio: 1.0
  use_trend_filter: true
  use_volume_filter: true
  entry_buffer_pct: 0.0
  stop_loss_pct: 0.01
  allow_counter_trend_shorts: true
  volume_timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
  volume_tf_mode: any
execution:
  post_only: false
  reduce_only_exits: true
  max_position: 1
  min_qty: 0.001
  qty_step: 0.001
  margin_mode: ISOLATED_MARGIN
  leverage: 4
  position_mode: ONE_WAY
  poll_interval_seconds: 30
  lookback_candles: 360
  taker_fee_bps: 6.0
  slippage_bps: 5.0
logging:
  level: DEBUG
  dir: logs
  json_output: true
monitoring:
  enable_metrics: true
  host: 0.0.0.0
  port: 9000
  recent_trades: 5
