symbol: BTCUSDT
category: linear  # bybit v5 category: linear | inverse | option | spot
mode: paper       # paper | live
risk:
  max_risk_per_trade_pct: 0.5
  daily_stop_r_multiple: -2.0
  cooldown_minutes: 3
  max_live_order_notional_krw: 50000.0
  usdt_krw_rate: 1350.0
  starting_equity: 10000.0
strategy:
  name: scalper_v1
  timeframe_entry: 1m
  timeframe_anchor: 5m
  ema_fast: 50
  ema_slow: 200
  atr_period: 14
  atr_mult_stop: 1.0
  partial_tp_r: 1.0
  trail_atr_mult: 1.5
  micro_high_lookback: 3
  time_stop_minutes: 15
execution:
  post_only: false
  reduce_only_exits: true
  max_position: 1
  min_qty: 0.001
logging:
  level: INFO
  dir: logs
  json_output: true
monitoring:
  enable_metrics: true
  host: 0.0.0.0
  port: 9000
  recent_trades: 5
